hngprojects/hng_boilerplate_python_fastapi_web

- .github/workflows/cd.dev.yml
- .github/workflows/cd.prod.yml
- .github/workflows/cd.staging.yml
- .github/workflows/ci.yml
- Added new GitHub Actions workflow files:
- `.github/workflows/ci.yml`
- `.github/workflows/cd.dev.yml`
- `.github/workflows/cd.staging.yml`
- `.github/workflows/cd.prod.yml`
These changes introduce automated Continuous Integration and Continuous Deployment pipelines to streamline our development process.
- Runs on push and pull requests to main, staging, and dev branches
- Sets up a test environment with PostgreSQL
- Prepares for running tests (test execution currently commented out)
- Separate workflows for dev, staging, and production environments
- Triggered after successful CI workflow completion
- Automates deployment process using SSH
1. Consistent build and test process across all branches
2. Automated deployments to respective environments
3. Reduced manual intervention, …
> added the cicd workflow files

- README.md
- alembic/env.py
- api/v1/models/__init__.py
- api/v1/routes/__init__.py
- api/v1/routes/auth.py
- api/v1/routes/newsletter_router.py
- api/v1/routes/roles.py
- main.py
This pull request improves the way models are imported in the alembic/env.py file by using a wildcard import from the api.v1.models package. Additionally, it introduces a base router for the FastAPI app, with a prefix of /api/v1, which will consolidate all endpoint routers.
​
​
​
> Refactor Alembic Model Imports and Create Base Router for FastAPI

- api/v1/routes/__init__.py
- api/v1/routes/activity_logs.py
- api/v1/schemas/activity_logs.py
- api/v1/services/activity_logs.py
- tests/v1/activity_logs/test_create_activity_log.py
​Created a Create Activity Log route
#494 
​This was a feature required to create activity log for users
​I wrote tests for this route
I tested with postman
​
​
> feat: create activity log

- api/v1/routes/newsletter.py
- api/v1/schemas/newsletter.py
- api/v1/services/newsletter.py
- tests/v1/newsletter/newsletter_test.py
- tests/v1/notification/test_get_user_nots.py
Create an API endpoint that allows an admin retrieve the emails​ of all newsletter subscribers
The changes include:
* **Endpoint Addition:** Added `GET /api/v1/pages/newsletters` for getting all newsletter subscribers
* **Error Handling:** Implemented checks for unauthorized access.
* **Testing:** Added `pytest` cases to ensure functionality and edge cases are covered.
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/549)
This feature is essential to enable administrators view the information about all newsletter subscribers.
* **Unit Tests:**
* Added tests to validate the retrieval of subscriptions from the database. 
* Also tests to validate authorization and authentication failures.
* **Test Environment:** Tests were run using a mocked database …
> feat: get newsletter subscribers

- tests/v1/testimonial/test_create_testimonial.py
fixed the endpoint route of the test file
​
The tests are failing because the route at the test files is not correct. it's pointing to the root url of the testimonials rather than the sub url of creating testimonials
​
- #79 
​
The tests are core part of development and ensuring each test passing is important thing to continue the development
​
This has been tested with pytest.
​
​
​
> fix: fixed create testimonial endpoint test

- api/v1/routes/testimonial.py
Fixed a bug that makes the get all testimonial endpoint return 500 instead of 422 on validation errors
​
While testing the  get all testimonial i noticed the endpoint returned 500 instead of 422 on validation errors
Before
​![Screenshot 2024-07-31 211437](https://github.com/user-attachments/assets/a7aa975b-4fa6-42fb-87ae-0b390eca63e6)
After
A  bug fix change
​
> bug fix : fixed bug in pagination for get all testimonials endpoint

- api/v1/routes/squeeze.py
- api/v1/schemas/squeeze.py
- api/v1/services/squeeze.py
- tests/v1/squeeze_page/test_fetch_squeeze.py
I've added the `GET /api/v1/squeeze/:id` and `GET /api/v1/squeeze` endpoints to retrieve squeeze pages. There is also an optional filter to sort the squeeze pages by state.
​
implemented a new endpoint to enhance the functionality of our platform. This addition is specifically designed to facilitate the retrieval of squeeze pages, which are essential for marketing campaigns and lead generation efforts. The integration of this feature marks a significant improvement in our service offerings, allowing users to efficiently access and manage their squeeze pages within our system.
​
- #643 
​
Fetching squeeze pages is essential for rendering them on the frontend.​
```
pytest
```
​
- fetch all squeeze pages (without filter)
- fetch squeeze page by id
- fetch squeeze pages (filtered by online …
> feat: fetch squeeze pages

- api/v1/routes/activity_logs.py
- api/v1/services/activity_logs.py
- api/v1/services/billing_plan.py
- tests/v1/activity_logs/test_get_a_user_activity_logs.py
**​ Description**
This pull request implements a new GET endpoint `api/v1/activity-logs/{user_id}` for fetching all activity logs of a specified user. This endpoint is intended for use by admin users only. The response will provide a structured JSON response containing the user's activity logs, including details such as action type and timestamps.
The expected JSON response format is as follows:
```json
{
"status": 200,
"message": "Activity logs fetched successfully!",
"data": {
"user_id": "str",
"id": "str",
"updated_at": "str",
"action": "str",
"timestamp": "str",
"created_at": "str"
}
}
```
**​ Related Issue**
[Issue #655](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/655)
**​ Motivation and Context**
This change is required to enable admin users to monitor …
> feat:fetch user activity logs

- api/v1/routes/permissions/roles.py
- api/v1/schemas/permissions/roles.py
- api/v1/services/permissions/role_service.py
- tests/v1/roles_permissions/roles_test.py
​
​This endpoint allows the super admin to delete a role.
This update introduces a new endpoint for users to delete roles. The changes include:
Endpoint: DELETE `/api/v1/roles/{role_id}`
Security: Roles are managed securely and deleted efficiently.
​[here #688](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/688)
​The change assists the super admin in managing roles by providing the ability to delete them when necessary.
This endpoint was tested using Postman and pytest.
​
​
​
> feat: Endpoint to delete a role by the super admin

- api/v1/routes/terms_and_conditions.py
- tests/v1/terms_and_conditions/test_create_terms_and_conditions.py
​
This PR adds a new POST endpoint to create Terms and Conditions. The endpoint is designed to be used by superadmins to initialize the system's Terms and Conditions.
​
This PR is linked to issue #738 
​
- Added new POST route at `/api/v1/terms-and-conditions/`
- Implemented logic to check for existing Terms and Conditions
- Added creation of new Terms and Conditions if none exist
- Utilized `UpdateTermsAndConditions` schema for input validation
- Implemented proper error handling and success responses
The new endpoint:
- Uses dependency injection for database session and superadmin authorization
- Checks if Terms and Conditions already exist before creating new ones
- Creates new Terms and Conditions entry if none exist
- Returns appropriate success or error responses
​
- Added unit …
> feat: Add endpoint to create terms and conditions with tests

- api/v1/routes/permissions/permisions.py
- api/v1/schemas/permissions/permissions.py
- api/v1/services/permissions/permison_service.py
- tests/v1/roles_permissions/test_update_perms.py
I created an endpoint that updates permissions on a role.
I added unit tests for the update permissions endpoint, including scenarios where the permission is not found, invalid, the user is not authorized, and a successful update.
​
​
This PR ensures that the update permissions functionality is thoroughly tested, handling various edge cases and verifying the correct behavior of the endpoint. It prevents potential bugs and ensures the robustness of the permissions update process.
This has been handled with pytest. The update permissions tests check for various edge cases and ensure the endpoint functions correctly.
​
​## WITHOUT VALID ROLE ID
​
> feat: added endpoint to update user permissions

- api/v1/routes/team.py
- api/v1/services/team.py
- seed.py
- tests/v1/team/test_get_all_team_members.py
Add GET `/api/v1/team/members` endpoint to retrieve all team members
This pull request introduces a new endpoint to fetch all team members and includes the corresponding tests to ensure its functionality. The new endpoint is `/api/v1/team/members`, which allows a super admin to retrieve all members of the team.
- Resolves issue #736.
This change is required to provide super admins with the ability to view all team members. It enhances the administrative capabilities of the application and ensures that team management is streamlined and efficient.
- **Unit Tests**: Implemented in `/tests/v1/team/[test_get_all_team_members.py](http://test_get_all_team_members.py/)`, covering the following scenarios:
- Successful retrieval of all team members.
- Handling cases where no team members are …
> feat: fetch all members in the team

- api/v1/routes/organization.py
- api/v1/services/organization.py
- scripts/org_seed.py
- tests/v1/faq/delete_faq_test.py
- tests/v1/faq/get_single_faq_test.py
- tests/v1/faq/update_faq_test.py
- tests/v1/organization/test_export_user_data.py
What I have done here is to add an endpoint to export relevant user data for users in a certain organization. This endpoint is a GET request: `/api/v1/organizations/{org_id}/users/export`
​
[Link to issue](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/752)
​
The change provides an added level of functionality to the entire application as a whole. As the endpoint is triggered, the csv data is downloaded immediately for the user to make use of.
​
This has been tested with Postman and Pytest to cover all scenarios and edge cases
Successful response
​
Organization not found error
Pytest
​
​
> feat: export organization users' data to csv

- api/v1/services/permissions/permison_service.py
- api/v1/services/permissions/role_service.py
- tests/v1/roles_permissions/permissions_test.py
- tests/v1/roles_permissions/roles_test.py
​
Updated the response structure in the relevant endpoints to use a custom success response format. This change standardizes the API response format, improving consistency and readability across the application.
​
​
The previous implementation did not use the custom success response, leading to inconsistencies in the API responses. This bugfix resolves the issue by ensuring that all success responses follow the same format, making it easier for clients to parse and handle responses.
​
This change has been tested by running unit tests on the updated endpoints to verify that the custom success response is returned correctly. Manual testing was also performed using Postman to ensure that the API behaves as expected and that the correct status codes and response bodies are returned.
​
​
​
> bugfix: updated response to use custom success response

- api/v1/routes/activity_logs.py
- api/v1/services/activity_logs.py
- tests/v1/activity_logs/test_delete_activity_log.py
- tests/v1/activity_logs/test_get_a_user_activity_logs.py
This pr introduces a new endpoint for deleting activity logs. The changes include:
-   **Endpoint:** `DELETE /api/v1/activity-logs/{id}`
-   **Functionality:** Allows authenticated super admins to delete an activity log by its ID.
-   **Authorization:** Only accessible by super admins.
-   **Response Handling:** Returns appropriate status codes and messages based on the outcome (success, unauthorized, forbidden, not found, server error).
**Related Issue:**
[Issue 765](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/765) - Implement  delete activity log endpoint
**Motivation and Context:**
This feature is necessary to provide administrators with the capability to manage and clean up activity logs. It ensures that logs can be removed when no longer needed, which …
> feat: delete an activity log

- api/v1/routes/invitations.py
- api/v1/services/invite.py
- tests/v1/invitation/test_delete_invitation.py
Create an API endpoint to allow superadmins delete invites.
This endpoint will validate the invite id and then delete the invite from the database.
​
The changes include:
* **Endpoint Addition:** Added `DELETE /api/v1/invite/{invite_id}` for deleting invites.
* **Error Handling:** Implemented checks for invalid invitation id and unauthorized access.
* **Testing:** Added `pytest` cases to ensure functionality and edge cases are covered.
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/779)
This feature is essential to enable superadmins delete invites from the database.
* **Unit Tests:** Added tests to validate the deletion of invites from the database, authorization failures and invalid request body.
* **Test Environment:** Tests were run using a …
> feat: endpoint to delete invites (superadmin)

- api/v1/routes/billing_plan.py
- api/v1/services/billing_plan.py
- tests/v1/billing_plan/test_update_billing_plan.py
The endpoint will update the billing plan using the plan's ID. **PATCH api/v1/organization/billing-plans/{plan_id} [PROTECTED]**
Implemented an endpoint to update a specific billing plan
[Issue link](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/796)
Different testing coverage was made with Postman
​
- [x ] New feature (non-breaking change which adds functionality)
​
- [x ] My code follows the code style of this project.
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.
> feat: update billing plan by plan_id

- api/v1/routes/permissions/roles.py
- api/v1/routes/product_comment.py
- tests/v1/product/test_product_comment.py
This PR implements the feature `api/v1/{product_id}/comments` to fetch all comments for a specific product. The endpoint has been adjusted to retrieve a list of all comments associated with a given product ID. Mocked services are used to test this functionality, ensuring that the correct data structure is returned with the appropriate status code.
This PR is related to [Issue #812](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/812) 
This change is required to allow users to retrieve all comments for a specific product in the system. It enhances the functionality by providing a way to gather feedback and reviews from users, which is essential for product evaluation.
This feature has been tested by creating unit tests using Pytest and MagicMock. The tests cover …
> feat: Fetch All Product Comments

- api/v1/routes/__init__.py
- api/v1/routes/user.py
- api/v1/services/user.py
- tests/v1/user/test_get_current_user_organizations.py
The change I have made is to get the organizations the current user belongs to. The endpoint accepts a GET reqyest. THis is the endpoint:
`/api/v1/users/organisations`
​
[Link to issue](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/519)
​
Th s solves the problem of not being able to get all the organizations you belong in as a current user
​
This has been tested with Postman and Pytest
​
​
​
> feat:  get current user organizations

- api/v1/routes/jobs.py
- tests/v1/job/test_fetch_all_jobs.py
**Summary of Changes**
Added a new endpoint `GET /api/v1/jobs` to fetch all job listings with pagination support.
**Description**
This update introduces the `GET /api/v1/jobs` endpoint, which allows clients to retrieve a list of job listings from the database. The response includes pagination information, such as total pages, total job listings, and details about each job, such as title, description, salary, company name, and other relevant attributes.
The response format is as follows:
```json
{
"status_code": 200,
"success": true,
"message": "Successfully fetched items",
"data":[
{
"department": dtr,
"author_id": UUID4,
"salary": str,
"company_name": str,
"created_at": datetime,
"title": str,
"description": str,
"location": str,
"job_type": str,
"id": UUID4,
"updated_at": datetime
}
]
} …
```
> feat: fetch all jobs

- api/v1/routes/auth.py
- api/v1/routes/user.py
- api/v1/schemas/user.py
- api/v1/services/user.py
- tests/v1/superadmin/test_admincreate.py
- tests/v1/user/change_user_password_test.py
This fix currently fixes the error the endpoint change from /api/v1/users/me/password to /api/v1/auth/change-password. The fix also allows users that signed up with socials to be able to set a password.
​
This fix currently fixes the error the endpoint change from /api/v1/users/me/password to /api/v1/auth/change-password. The fix also allows users that signed up with socials to be able to set a password.
Users that signed up via socials usually do not have passwords set up, meaning they would always have to login using their social accounts, the fix here enables them set a password for their account at convenience, that way, they can then be ale to login with a password and email if they wished. The fix also improved on the allowed special characters for password and the exception of …
> fix: Fixed password update endpoint

- api/v1/routes/topic.py
- api/v1/schemas/topic.py
- api/v1/services/topic.py
- tests/v1/topic/test_topic.py
​
Resolved issues with the help center endpoints that were not processing correctly. Also fixed the Help Center GET filter endpoint by removing the request body and corrected the placement of the topic ID.
​
​
These changes are necessary to ensure the help center endpoints function correctly. The changes address the incorrect processing of requests, eliminates the request bodies in the GET filter endpoint, and corrects the placement of the topic ID.
Unit tests were written and carried out for this endpoint using the Pytest library.
​
​
​
> fix: fixed help center to integrate with frontend

- .github/workflows/cd.dev.yaml
- .gitignore
- t
> chore: updated gitignore

- api/v1/services/contact_us.py
​
This update removes the dependency on the org_id field when submitting data to the ContactUs table. The org_id is no longer passed during the form submission process, allowing users to submit contact requests without needing an associated organization ID.
​
​
This change is required to make the contact form usable to users who do not have an associated organization. The submission process initially depended on the org_id field, preventing unauthenticated users to submit contact requests
​
​
​
> fix: removed orgid from being passed to ContactUs table

- api/v1/models/billing_plan.py
- api/v1/routes/stripe.py
- api/v1/schemas/plans.py
- api/v1/services/billing_plan.py
- tests/v1/billing_plan/test_billing_plan.py
- tests/v1/billing_plan/test_get_billing_plan.py
- tests/v1/billing_plan/test_update_billing_plan.py
​
The logic in the Billing Plan creation method has been adjusted to ensure that a billing plan with the same name can only exist once across both "monthly" and "yearly" durations. Specifically:
- Added checks to ensure that a billing plan with the same name cannot be created if it already exists for both "monthly" and "yearly" durations.
- Applied a 20% discount to the yearly plan price if the duration is "yearly."
- Improved error handling to provide clear messages when attempting to create a duplicate plan.
​
​
This change is required to prevent users from creating multiple billing plans with the same name across both "monthly" and "yearly" durations. This will help maintain the integrity of billing plans and ensure that each plan name is unique within its duration context.
​
The …
> bugfix:  fix logic for billing plan creation to handle duplicate plan names across monthly and yearly durations

- api/v1/routes/auth.py
- api/v1/schemas/request_password_reset.py
- api/v1/schemas/token.py
- api/v1/schemas/user.py
- tests/v1/auth/test_request_pwd_reset.py
- tests/v1/auth/test_signup.py
- tests/v1/auth/test_token_auth.py
- tests/v1/auth/test_verify_magic_link.py
- tests/v1/squeeze_page/test_create_squeeze.py
- tests/v1/squeeze_page/test_fetch_squeeze.py
- tests/v1/terms_and_conditions/test_update_terms_and_conditions.py
This Pull Request is intended to correct the bug that allows users to use an invalid email(non-existing domain part) for registration, login, request-magic-link, and reset-password.
​
This Pull Request is intended to correct the bug that allows users to use an invalid email(non-existing domain part) for registration, login, request-magic-link, and reset-password.
Prior to this PR, users were able to register, login with an invalid email like johnson.pragui@gmail.com.com or johnson.oragui@example.com, but with this fix, the email validation on these four endpoints mentioned above are now properly validated.
​
[Invalid email on login](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/832)
[Invalid email on registration](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/ …
> fix: Fixed the bug on email validation

- api/v1/routes/auth.py
- api/v1/schemas/user.py
- tests/v1/user/change_user_password_test.py
This pull request is intended to change the http method of password change from patch to put, and rename the endpoint from /api/v1/auth/change-password to /api/v1/auth/password, and add a new field: confirm_new_pasword.
​
This pull request is intended to change the http method of password change from patch to put, and rename the endpoint from /api/v1/auth/change-password to /api/v1/auth/password, and add a new field: confirm_new_pasword.
​
[modify password update endpoint](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/923)
​
​
​This has been tested with pytest and postman
​
​
> fix: Fixed password update http method from PATCH to PUT

- api/core/dependencies/email/templates/faq-feedback.html
- api/utils/send_mail.py
- api/v1/models/__init__.py
- api/v1/models/faq_inquiries.py
- api/v1/routes/__init__.py
- api/v1/routes/faq_inquiries.py
- api/v1/schemas/faq_inquiries.py
- api/v1/services/faq_inquiries.py
- tests/v1/faq-inquiries/test_faq_inquiries.py
​
This update handles the submission process for the additional inquiries form on the contact page and implements an email notification feature to provide feedback upon successful submission.
​
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/878
​
This change is necessary to ensure that users receive confirmation when their inquiries are submitted through the contact page. The added email feedback functionality enhances user experience by providing immediate acknowledgment of their request, improving communication and user satisfaction.
​
Apprpriate unit tests have been carried out using the Pytest library
​
​
​
> feat: post user faq inquiries form

- api/core/dependencies/email/templates/profile_recovery_email.html
- api/v1/models/profile.py
- api/v1/routes/profiles.py
- api/v1/routes/user.py
- api/v1/schemas/profile.py
- api/v1/schemas/user.py
- api/v1/services/profile.py
- api/v1/services/user.py
- tests/v1/profile/test_upload_profile_image.py
- tests/v1/profile/test_user_profile.py
- tests/v1/profile/user_update_profile_test.py
- tests/v1/user/test_updateuser.py
This Pull request aims to remove the change of email from /users and /profile endpoint. The change of user email is now moved to PUT /profile, and a user email can only be changed from email confirmation for security reason and to ensure data integrity.
​
This Pull request aims to remove the change of email from /users and /profile endpoint. The change of user email is now moved to PUT /profile, and a user email can only be changed from email confirmation for security reason and to ensure data integrity.
​
[[FIX] Include the addition of social links in the profile update #935](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/935)
[[FIX] Remove the email from fields to be updated on users profile. #937](https://github.com/hngprojects/hng_boilerplate_python_fastapi_we …
> fix: Removed email change from user and profile update, added separate route for recovery email update

- api/core/dependencies/email/templates/unsubscribe.html
- api/v1/routes/newsletter.py
- tests/v1/newsletter/test_newsletter_unsubscribe.py
This pull request implements a feature that sends a confirmation email to users when they unsubscribe from a newsletter. The confirmation email includes details about the successful unsubscription, provides information on how to resubscribe if the user changes their mind, and optionally gathers feedback on why they unsubscribed. This enhancement improves user communication and helps ensure a positive user experience.
​
This feature was discussed in the following issue: [Send confirmation email on newsletter unsubscription](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/947)
​
​This change is required to improve user experience by providing clear communication when users take the action of unsubscribing from a newsletter. Without a confirmation, users may be …
> feat: added feature to send email when user unsubscribes from a newsletter

- api/v1/routes/billing_plan.py
- api/v1/schemas/base_schema.py
- api/v1/schemas/plans.py
- api/v1/services/billing_plan.py
Update billing plan endpoints docs to show samples of expected data so frontend developers can easily integrate with the backend. Endpoint docs updated include:
- /api/v1/organisations/{organisation_id}/billing-plans
- /api/v1/organisations/billing-plans
- /api/v1/organisations/billing-plans/{billing_plan_id}
- /api/v1/organisations/billing-plans/{billing_plan_id}
[[FIX]: Add Expected Data Samples To Docs For All Billing Plan Endpoints #941](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/941)
Frontend developers and others viewing the backend docs should be able to know exactly what to expect from each endpoint.
* **Unit Tests:** Added tests to validate successful and failed requests as expected.
* **Test Environment:** Mocked database; to avoid interference with …
> enhancement: update billing plan endpoints docs to show sample return data

- api/v1/routes/faq.py
​
Added search functionality to the FAQ endpoint. The updated /faqs GET endpoint now allows filtering of FAQs based on a keyword provided by the user. The search checks both the question and answer fields for matches. If a keyword is provided, it returns the relevant FAQs; otherwise, it returns all FAQs.
​
[Related Issue](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/904)
​
This change was required to enhance the user experience by enabling more effective and accurate search functionality on the FAQ page. It allows users to quickly find relevant information by searching through both the questions and answers, ensuring that all relevant FAQs are returned based on the user’s query.
​
The changes were tested using Postman by running the FastAPI application locally. The testing …
> feat: Added search queries functionality to fags

- api/v1/models/__init__.py
- api/v1/models/api_status.py
- api/v1/routes/__init__.py
- api/v1/routes/api_status.py
- api/v1/schemas/api_status.py
- api/v1/services/api_status.py
- tests/v1/status_page/test_post_status.py
- update_api_status.py
​
This pull request implements a backend API for the API Status Page. It includes endpoints to update and retrieve API status information, a database model to store the data, and a script to parse and post results from Newman test runs.
​
#952 
​
This change is required to create a robust backend system that can efficiently process, store, and serve API health data. It solves the problem of real-time monitoring and displaying the health of various API groups, enabling automatic updates every 15 minutes on all projects and boilerplates.
​
Unit tests were written and carried out on the GET and POST endpoints using the Pytest library
​
​
> feat: implement status page endpoints

- api/v1/routes/blog.py
- api/v1/services/blog.py
- tests/v1/blog/test_delete_blog_dislike.py
An endpoint to enable users who previously `disliked` a blog post to remove the `dislike`.
[[FEAT]: Endpoint To Delete Blog Dislike #966](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/966)
Readers should be able to remove **dislike** from a particular post after adding one, if they posted it in error or just changed their mind.
* **Unit Tests:** Added tests to validate successful and failed requests as expected.
* **Test Environment:** Mocked database; to avoid interference with the production environment.
* **Postman:** Validation test has also been run on postman API tester, with screenshots attached below.
***
Enable `/api/v1/blogs/{blog_id}/dislike` endpoint  to automatically remove existing `like` by the `current_user` before creating new `dislike`, and …
> feat: delete blog dislike

- api/v1/routes/blog.py
- api/v1/services/blog.py
- tests/v1/blog/test_delete_blog_like.py
An endpoint to enable users who previously `liked` a blog post to remove the `like`.
[[FEAT]: Endpoint To Delete Blog Like #965](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/965)
Readers should be able to remove **like** from a particular post after adding one, if they posted it in error or just changed their mind.
* **Unit Tests:** Added tests to validate successful and failed requests as expected.
* **Test Environment:** Mocked database; to avoid interference with the production environment.
* **Postman:** Validation test has also been run on postman API tester, with screenshots attached below.
***
Enable `/api/v1/blogs/{blog_id}/like` endpoint  to automatically remove existing `dislike` by the `current_user` before creating new `like`, and vice versa with …
> feat: delete blog like

- api/v1/models/billing_plan.py
- api/v1/routes/stripe.py
- api/v1/schemas/stripe.py
- api/v1/services/billing_plan.py
- api/v1/services/stripe_payment.py
- tests/v1/billing_plan/test_stripe.py
​
This PR introduces functionality that allows users to upgrade or downgrade their subscription plans within the application. The implementation includes:
- A new endpoint to handle plan upgrades and downgrades.
- Validation to ensure users can only switch to valid plans.
- Logic to prorate charges or credits based on the current billing cycle.
- Integration with Stripe to handle the necessary payment adjustments.
- Database updates to reflect the new subscription plan and billing cycle.
​
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/876
​
This change is required to provide flexibility to users who may need to adjust their subscription plans due to changes in their usage requirements. By enabling plan upgrades and downgrades, we aim to enhance the user experience and cater …
> feat: handle plan transition logic for "Upgrade" and "Downgrade" on Payment 

- api/core/dependencies/email/templates/squeeze.html
- api/v1/routes/squeeze.py
- api/v1/services/squeeze.py
- tests/v1/squeeze_page/test_create_squeeze.py
- tests/v1/squeeze_page/test_fetch_squeeze.py
​
This pull request introduces email service functionality to the squeeze page. When a user signs up on the squeeze page, a confirmation email is automatically sent to their provided email address. This enhancement ensures better user engagement and confirmation of their subscription or sign-up.
​
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/930#issue-2483721921
​
This change is required to enhance user experience by providing immediate feedback in the form of a confirmation email when they sign up. It helps ensure that the email provided is valid and gives the user a sense of completion after their sign-up action. This is crucial for maintaining user engagement and ensuring that only valid users are added to the database.
​
- Unit tests were created to ensure that the …
> fix: added email service to squeeze sign up

- update_api_status.py
​
Implemented a fix for the invalid data comparison in the status page script.
​
​
This change addresses the issue of incorrect data comparison in the status page script, ensuring accurate and reliable data processing for API status reporting.
​
​
​
​
> fix: status page script

- api/v1/routes/email_template.py
- api/v1/schemas/email_template.py
- api/v1/services/email_template.py
- seed.py
- tests/v1/email_template/test_send_email_template.py
​
Implemented the functionality to send email templates. This includes robust error handling, retry mechanisms, and detailed logging to ensure that failures in sending emails do not disrupt the user experience. Additionally, ensured that user data is securely saved even if the email sending process fails. Unit tests were added to cover both successful and failure scenarios related to sending email templates.
​
[Related issue](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/930)
​
This change is required to provide a reliable mechanism for sending email templates as part of the user interaction workflow. It solves the problem of potential data loss or user experience issues caused by failures in the email sending process. By adding retries and logging, the system becomes more …
> feat: Added send email template endpoint
