.github/workflows/cd.dev.yml
.github/workflows/cd.prod.yml
.github/workflows/cd.staging.yml
.github/workflows/ci.yml

- Added new GitHub Actions workflow files:
- `.github/workflows/ci.yml`
- `.github/workflows/cd.dev.yml`
- `.github/workflows/cd.staging.yml`
- `.github/workflows/cd.prod.yml`
These changes introduce automated Continuous Integration and Continuous Deployment pipelines to streamline our development process.
- Runs on push and pull requests to main, staging, and dev branches
- Sets up a test environment with PostgreSQL
- Prepares for running tests (test execution currently commented out)
- Separate workflows for dev, staging, and production environments
- Triggered after successful CI workflow completion
- Automates deployment process using SSH
1. Consistent build and test process across all branches
2. Automated deployments to respective environments
3. Reduced manual intervention, …

added the cicd workflow files

---

.github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md

@zxenonx the pr template has been added kindly check it out

pr template to enforce good pr

---

.env.sample
.github/workflows/cd.dev.yml
.github/workflows/cd.prod.yml
.github/workflows/cd.staging.yml
.github/workflows/ci.yml

added ci step test main.py, renamed cd pipelines accordinly and commented out alembic migration

added ci step test main.py, renamed cd pipelines accordinly and commented out alembic migration

---

api/v1/models/blog.py
seed.py

**Summary:**
This pull request introduces updates to the `Blog` model and the `seed.py` file. The following changes have been made:
1. **Blog Model Updates:**
- Added new fields to the `Blog` model:
- **`is_deleted`**: A boolean field to handle the soft deletion of blog posts.
- **`excerpt`**: A brief excerpt or summary of the blog post.
2. **Seed Data Updates:**
- Updated `seed.py` to include sample data for the newly added fields in the `Blog` model.
- Ensured that all required fields are populated for blog entries.
**Migration Note:**
- As part of this update, database migrations need to be applied to ensure the new fields are created in the database.
**Note**: This update is urgent and necessary so that interns who are working on the Blog API endpoints can fully have a complete db …

Update blog model with new fields and added blog creation to seed data

---

.github/workflows/cd.dev.yml
.github/workflows/cd.prod.yml
.github/workflows/cd.staging.yml

added database migration to the cd workflows​
added `alembic upgrade head` to the devops cd pipelines i.e cd.dev.yml, cd.staging.yml and cd.prod.yml

added database migration to the cd workflows

---

api/utils/dependencies.py
api/v1/routes/auth.py

​
This pull request fixes a bug with the `OAuth2Scheme` for authenticating user login
This issue arises when a user attempts to access the login route using their login credentials.
Two errors occur:
1. The login route throws a 404 not found as `OAuth2PasswordBearer(tokenUrl="login")` is currently set to the route `/login`, rather than the conventional `/api/v1/auth/login​`.
2. The function handling the `login` route fails to add `OAuth2PasswordRequestForm` as a dependency in one of its parameters,  thereby causing the `username` and `password` to be incorrectly fetched from the user.
This change fixes the **OAuth Scheme** implementation present in the codebase, so that it doesn't return an error when a valid user attempts to login with their `username` and `password`
​​
Login route …

bug: This commit fixes a login issue with the OAuth Scheme

---

.github/workflows/ci.yml

running tests in ci

---

.github/workflows/ci.yml

upgraded the python ci version to 3.10

upgraded the python ci version to 3.10

---

.github/workflows/ci.yml

added caching while installing dependencies

added caching while installing dependencies

---

main.py

This pull request introduces a new endpoint for managing subscription plans. Admins can now create various subscription plans with details including name, description, price, duration, and features. The changes include:
- **Endpoint Addition:** Added `POST /api/v1/plans` for creating new subscription plans.
- **Error Handling:** Implemented checks for duplicate plans and unauthorized access.
- **Database Models:** Updated the database schema to include a `SubscriptionPlan` model.
- **Testing:** Added pytest cases to ensure functionality and edge cases are covered.
---
[Issue Ticket](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/37)
---
This feature is essential to allow admins to create and manage different subscription plans, which is critical for the …

Fixed Create Plan Subscription

---

main.py

Reverts hngprojects/hng_boilerplate_python_fastapi_web#194

Revert "Fixed Create Plan Subscription"

---

api/v1/routes/facebook_login.py

The Facebook login route is utilizing a distinct tag compared to the Authentication group.
​
I've updated the tag to correspond with the auth group, ensuring it displays correctly in the Swagger UI documentation.
​
- https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/55
​
Grouping the authentication endpoints together will facilitate easy access, making them simpler to navigate, and more straightforward to maintain or update as needed.
​
N/A
​
> before 
> after
​
​

chore: update the tag of facebook-login route

---

api/v1/schemas/activity_logs.py
api/v1/services/activity_logs.py
tests/v1/activity_logs/test_create_activity_log.py

​
​This pr fixes the user id format for activity log
​
​This was necessary to allow users create activity log
​Tests were written for this
​
​

fix: change activity log user_id format

---

api/v1/routes/google_login.py
tests/v1/test_google_oauth.py

​
​fix redirect url for google auth
​
​Change the route and redirect url
​all tests pass
​
​

fix: google redirect url

---

api/v1/routes/blog.py
api/v1/schemas/comment.py
api/v1/services/comment.py
tests/v1/comment/test_fetch_all_comments.py

api/v1/blogs/{blog_id}/comments?page=1&per_page=20
This endpoint retrieves comments associated with a single blog and the likes and dislikes associated with each comment.
​
Added a comment schema for comment related response. Created a service class to handle operations related to retrieving comments linked to a blog. The endpoint api/v1/blogs/{blog_id}/comments?page=1&per_page=20 will retrieve comments linked to the blog with the id, if the blog_id is a valid one. And the endpoint also works with pagination with 20 as the maximum page size.
​
[Endpoint to retrieve all comments for a single blog.](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/486)
​
The new Feature is required because of the necessity to display every comment that is linked to a specific blog.
​ …

feat: add Endpoint to retrieve all comments for a single blog

---

tests/v1/notification/test_get_user_nots.py

The notifications.test.js file contained a failing test that was causing our CI/CD pipeline to break. This pull request addresses the issue and ensures that all tests pass successfully.
- Bug Fix: Corrected the failing test case in the notifications.test.js file.
- Updated the expected output to match the current implementation.
- Fixed the setup for the test to ensure it reflects the correct state before running assertions.
- Modified mock data to align with the latest changes in the notification service.
- Ran the full test suite locally and confirmed that all tests pass.
- Verified that the specific test case now works as expected.
- Ensured no other tests were affected by these changes.
​
This has been tested extensively using pytest
​
​

fix: update test to get user notifications

---

api/v1/routes/testimonial.py
api/v1/schemas/testimonial.py
api/v1/services/testimonial.py
tests/v1/testimonial/test_create_testimonial.py

Added create testimonials endpoint `POST api/v1/testimonials`
​
Implementing an endpoint for the submission of user testimonials is a valuable addition to any service, providing a platform for users to share their experiences and feedback. This not only enhances the credibility of the service but also offers insights into user satisfaction and areas for improvement. By enabling a direct channel for testimonials, users can contribute to the service's reputation and help shape its future development.
​
- #79 
​
The completion of the testimonials feature necessitates the implementation of this endpoint to address the underlying issue effectively.
​
This endpoint has undergone testing using PyTest and postman
​
​
​

feat: create testimonial

---

api/v1/routes/user.py
api/v1/schemas/user.py
api/v1/services/user.py
tests/v1/user/test_get_all_users.py

GET api/v1/users?page=1&per_page=10
This endpoint retrieves all users. And only the super admin can access this endpoint. The endpoint also filters users based on the valid params. GET (eg. api/v1/users?page=1&per_page=20&is_active=true&is_verified=true). The endpoint allows filtering using more than one valid params (e.g api/v1/users?page=1&per_page=20&is_deleted=true)
​
Added a Response schema for the response. Created a service class method to handle operations related to retrieving users. The endpoint GET api/v1/users?page=1&per_page=20 will retrieve users when accessed by the super admin. And the endpoint also works with pagination with 10 as the maximum page size. The endpoint filters users based on the params passed which are attributes of a given user.
​
Add endpoint to fetch all …

feat: add endpoint to fetch all users for super admin #

---

api/v1/routes/organization.py
api/v1/services/organization.py

Endpoint to retrieve all organizations
​
​
​
all organizations information needs to be displayed on the dashboard​
​
​
​

feat: Endpoint to retrieve all organizations

---

api/v1/routes/__init__.py
api/v1/routes/api_tests.py
api/v1/services/api_tests.py

feat: add testers route

---

api/utils/success_response.py
api/v1/routes/auth.py
tests/v1/profile/test_user_profile.py
tests/v1/testimonial/test_fetch_single_testimonial.py
tests/v1/user/change_user_password_test.py
tests/v1/user/test_getuser.py
tests/v1/user/user_deactivation_test.py

Update login success response
Include access token in user object
​Updated auth.py 
​
​
​To comply with all format, access_token was added to user object
​
​

fix: update login success response

---

api/v1/routes/product.py
api/v1/schemas/product.py
api/v1/services/product.py
tests/v1/product/test_status.py

This update introduces an API endpoint `api/v1/products/status` that allows authenticated users to filter products based on their stock status. The endpoint performs the following:
-   Validates the user's authentication and authorization.
-   Returns a list of products filtered by the specified stock status.
-   Handles various scenarios, including:
-   Successful data retrieval for valid requests.
-   Unauthorized access with a 401 status code for requests without proper authentication.
-   Forbidden access with a 403 status code for users without sufficient permissions.
-   Server errors with a 500 status code for unexpected issues.
The endpoint supports a query parameter `status`, which is required and can be one of the following stock statuses: `in_stock`, `out_of_stock`, or …

feat:  endpoint  to filter products by status (in_stock, out_of_stock, low_on_stock) 

---

api/v1/models/product.py
api/v1/routes/waitlist.py
tests/v1/waitlist/test_add_user_waitlist.py
tests/v1/waitlist/waitlist_test.py

**Description:**
This pull request includes the following changes:
1. **ProductFilterStatusEnum Update:**
- Updated the `ProductFilterStatusEnum` values to 'active' and 'draft'. This change ensures consistency with the values used in the frontend page, facilitating smoother integration between frontend and backend.
2. **API Router Prefix Change:**
- Changed the API router prefix from "/waitlists" to "/waitlist". This update aligns the route naming with the specification outlined in the doc file, ensuring consistency with the documented API structure.`` 
**Related Issues (Link to issue ticket):**
[# add user to waitlist](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/238)
[# API endpoint for waitlist user …

feat: update filter status  and endpoint url

---

alembic/versions/836938cb4ce1_merge_heads.py

This PR is to fix the current migration issues with alembic heads
​
This PR is required so migrations work properly and without issues
​
No test was run for this change
​
​
​

fix: fix alembic heads issues

---

api/v1/routes/jobs.py
api/v1/schemas/jobs.py
api/v1/services/jobs.py
tests/v1/job/test_update_jobs.py

Endpoint to update a job by the super admin
​
This endpoint, allows the super admin to update a job posting
​
This update introduces a new endpoint for users to upload profile images. The changes include:
**Endpoint:** `PATCH /api/v1/jobs/{id}`
Security: Images are stored securely and managed efficiently.
​
​The change assist the super admin to mak corrections or changes to the job listing 
This endpoint was posted on postman, and also pytest.
​
​
​

feat: Worked on the update jobs by ID and test

---

api/v1/routes/permissions/roles.py
api/v1/schemas/permissions/roles.py
tests/v1/roles_permissions/roles_test.py

fixed the `api/v1/roles/{role_id}` response body
[#687](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/pull/687)
​
​This endpoint allows the super admin to delete a role.
This update introduces a new endpoint for users to delete roles. The changes include:
Endpoint: DELETE `/api/v1/roles/{role_id}`
Security: Roles are managed securely and deleted efficiently.
​[here #688](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/688)
​The change assists the super admin in managing roles by providing the ability to delete them when necessary.
This endpoint was tested using Postman and pytest.
​
​
​

fix: Endpoint to delete a role by the super admin

---

api/v1/services/job_application.py

I updated the service to create job applications to handle cases where the user has already applied for a particular job and they want to apply again
​
[Link to issue](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/703)
​
This PR handles the edge case in the description above and it prevents a bug where once a user applies for a job, they won't be able to apply for another job.
​
THis test has been handled with pytest
​
​
​

fix: fix job application creation to handle bug of user only being able to apply for one job only

---

api/utils/settings.py
api/v1/routes/terms_and_conditions.py
api/v1/schemas/terms_and_conditions.py
api/v1/services/terms_and_conditions.py
tests/v1/terms_and_conditions/test_delete_terms_and_conditions.py

Implemented and tested the feature for deleting Terms and Conditions at the endpoint `api/v1/terms-and-conditions/{id}`. This feature allows authenticated users with appropriate permissions to delete terms and conditions records. Includes improvements in handling authentication and error responses.
- Added functionality to the `api/v1/terms-and-conditions/{id}` endpoint to allow deletion of terms and conditions.
- Integrated token-based authentication to secure the endpoint.
- Implemented validation to handle non-existent terms and conditions records.
- Added detailed error responses for various scenarios including invalid tokens and non-existent terms and conditions.
- Updated tests to ensure proper functionality and error handling.
The delete feature for terms and conditions allows …

feat: delete terms and conditions

---

api/v1/routes/terms_and_conditions.py
api/v1/services/terms_and_conditions.py
tests/v1/terms_and_conditions/test_get_terms_and_conditions.py

​
This pull request implements a new GET /terms-and-conditions/{id} endpoint to retrieve terms and conditions by their unique ID. The endpoint queries the database and returns the terms and conditions if found, or a 404 Not Found response if the specified ID does not exist.
​
#737 
​
This change is required to allow users to retrieve specific terms and conditions based on their ID, which is a common feature in many applications for providing detailed information on terms and conditions. It ensures the application can handle both valid and invalid ID requests appropriately.
​
​Testing was conducted using pytest and  SwaggerUI in a local development environment. All new tests passed, and existing functionality was unaffected.
1. not found
2. found
​
​

feat: get terms and conditions based on id

---

api/v1/routes/settings.py
api/v1/schemas/data_privacy.py
api/v1/services/data_privacy.py
tests/v1/settings/test_update_data_privacy_settings.py

I implemented a new `PATCH` endpoint for user data privacy settings, this endpoint allows users to modify their data privacy settings.
- Implemented a new endpoint for data privacy settings modification
- Added validation checks for request body
- Developed server-side logic to handle data privacy settings modification
- Wrote tests for the new endpoint
Based on issue #694
This change introduces an endpoint that allows users to modify their data privacy settings.
The endpoint was tested manually using Postman and programmatically with automated tests.
- **Unit Testing:** Conducted tests covering endpoint functionality, authentication logic, validation, and error handling.
- **Integration Testing:** Performed end-to-end testing to ensure seamless operation within the application.
- …

feat: implement endpoint to update data privacy settings

---

api/v1/routes/product.py
api/v1/schemas/product.py
api/v1/services/product.py
tests/v1/product/test_new_product_category.py

​
Implemented a POST request endpoint to create a new product category.
​
Linked to #645 
​
This feature is essential to enable admins create a new category for products.
​
Unit tests were written and carried out for this endpoint using the Pytest library.
​
​
​

feat: create new product category

---

api/v1/routes/permissions/roles.py
api/v1/services/permissions/role_service.py
tests/v1/auth/test_token_auth.py
tests/v1/notification/test_delete_notification.py
tests/v1/notification/test_get_user_nots.py
tests/v1/roles_permissions/test_get_roles.py

This pull request includes changes that address the issues encountered with fetching roles for a specific organization and unauthorized access handling. The updates ensure the proper validation of authentication and provide meaningful responses.
Related Issue
No specific issue ticket linked.
This change is required to ensure that the roles for a specific organization can be fetched correctly by authorized users and that unauthorized access attempts are handled properly with appropriate error messages.
Tested the endpoint for fetching roles for an organization with valid and invalid organization IDs.
Verified the response for unauthorized access to ensure proper error handling.
Ensured all existing tests pass with the new changes.
Screenshots
Screenshot 2024-08-06 at 14 18 05
Bug fix …

feat:get roles in an organization

---

.github/workflows/pr-deploy.yml
Dockerfile

Dr in tech22 patch 1

---

api/v1/routes/google_login.py
api/v1/services/google_oauth.py
tests/v1/test_google_oauth.py

This PR covers changes made to Google authentication. I have fixed issues relating to incorrect payload format being returned after successful authentication and also addressed the creation of a default organization for the user after successful authentication for the first time.
​
​
This PR solves the problem of incorrect payload being returned and also corrects the issue of getting user data from Google from the wrong Google endpoint. 
​
This has been tested using Swagger and Pytest
​
Request
Response
​
​

fix: fix incorrect response in google authentication endpoint

---

.github/workflows/cd.dev.yml
.github/workflows/cd.prod.yml
.github/workflows/cd.staging.yml

adjusted the docker compose command
​
​
​
​
​
​
​

Sarahligbe patch 1

---

api/v1/routes/product.py
tests/v1/product_comment/test_update_product_comment.py

This endpoint updates a products comment 
​
The endpoints update a certain product comment by its id. It allows users who have made comments about a certain product , edit their comments about that product.  
​
​
The endpoint allow users edit thier product properly 
​
​
​
- [] Bug fix (non-breaking change which fixes an issue)
​

feat: added update product comment

---

api/v1/routes/google_login.py
api/v1/services/google_oauth.py
tests/v1/test_google_oauth.py

I added email sending for Google authentication. So when a user logs in with Google for the first time, they receive a welcome email
​
This is to provide added functionality for the authentication process.
​
This has been tested with pytest
​
​
​

fix: fix email sending after social auth for the first time

---

tests/v1/billing_plan/test_get_billing_plan.py

​
This PR addresses an issue with the billing plan test case. The test case has been updated to correctly validate the expected behavior of the billing plan functionality.
​
​
The billing plan test case was not functioning as intended, leading to potential inaccuracies in the test suite. This fix ensures that the billing plan functionality is properly tested and validated, improving the overall reliability of the application.
​
- The fixed billing plan test case was executed and passed, confirming the correctness of the billing plan functionality.
- Additional unit tests were run to ensure that the fix does not introduce any regressions.
- Integration tests were conducted to validate that the billing plan works as expected in the broader context of the application.
​
​
​

bugfix: fixed billing test

---

.dockerignore

​created a dockerignore file
​
​
​
​
​
​

Include .dockerignore file

---

api/v1/routes/auth.py
requirements.txt
tests/v1/profile/test_upload_profile_image.py
tests/v1/profile/test_user_profile.py
tests/v1/squeeze_page/test_create_squeeze.py
tests/v1/squeeze_page/test_fetch_squeeze.py
tests/v1/superadmin/test_admincreate.py
tests/v1/terms_and_conditions/test_update_terms_and_conditions.py
tests/v1/testimonial/test_create_testimonial.py
tests/v1/testimonial/test_fetch_single_testimonial.py
tests/v1/user/change_user_password_test.py
tests/v1/user/test_get_users_by_role.py
tests/v1/user/test_getuser.py
tests/v1/user/user_deactivation_test.py

I made changes to the authentication response
​
The reason for this is to match what is on the frontend
​
This has been done with pytest.
​
​

fix: fix auth response

---

.github/workflows/cd.dev.yml
.github/workflows/cd.prod.yml
.github/workflows/cd.staging.yml
.github/workflows/pr-deploy.yml

DrInTech22-patch-1

---

api/v1/routes/auth.py

This fix currently fixes the error thrown when two different users has the same first name and trying to register.
​
This fix currently fixes the error thrown when two different users has the same first name and trying to register.
The first user would get registered successfully and an organization created for the user, but the second user with the same first name would have an account created, but no organization created because of organization name duplication, as the first name of users are used to create an organization for them on sign up. This fix solves that issue by using the user's email address as the organization name, that way every organization name would be unique as the user email is unique.
​
[]()
​
This fix solves the issue of organization name duplication on user …

fix: fixed organization name duplication after user registration

---

api/v1/routes/stripe.py

​
- updated cancel and success response.
​
hese changes are required to improve the robustness of the application by handling response 
​

bugfix: updated success and cancel request response

---

api/v1/services/google_oauth.py

This fix corrects the exception thrown when two different users with same first name signs up using google, it allows users with same first name to have organizations created for them.
​
This fix corrects the exception thrown when two different users with same first name signs up using google, it allows users with same first name to have organizations created for them.
​
​
​
This fix did not break any test for google oauth.
​
​
​

fix: fixed bug in creating organization after user signs up with google

---

api/core/dependencies/email/templates/signin.html
api/utils/send_mail.py
api/v1/routes/auth.py
tests/v1/auth/test_magic_link.py

This fix provides a solution to when a user requests a sign in link to email, an actual link embedded in a template is sent to the user.
​
This fix provides a solution to when a user requests a sign in link to email, an actual link embedded in a template is sent to the user. With this fix, a user would get a link associated with a token in the params for sign in.
​
​
​
This has been tested with postman and pytest
​
Post request to magic link andpoint
Link received in email of the user
​pytests
​

fix: Fixed magic link sign-in

---

api/v1/routes/stripe.py
api/v1/services/stripe_payment.py

​
This pull request modifies the response structure of the specified endpoint to dynamically adjust based on the request from the frontend. The change ensures that the data returned is tailored to the specific needs of the frontend, improving efficiency and user experience.
​
​
This change is required to ensure that the backend can provide responses that are more aligned with the requirements of the frontend. It addresses the issue of unnecessary data being sent to the frontend, which can lead to performance inefficiencies and a suboptimal user experience.
​
The change was tested using unit tests and integration tests in a development environment. The tests included sending various requests from the frontend and verifying that the responses were correctly tailored based on the request …

bugfix: update endpoint response based on frontend request

---

api/v1/routes/__init__.py
api/v1/routes/newsletter.py

​
I changed the route for the POST request from ``` api/v1/newsletters/subscribers ``` to ``` api/v1/newsletter-subscriptions ``` to better reflect the purpose of the endpoint. This change is part of an ongoing effort to improve the clarity and consistency of our API routes.
​
​The previous route name ``` api/v1/newsletters/subscribers ``` was a bit ambiguous and could be misinterpreted as a route that manages only the subscribers. Changing it to ``` api/v1/newsletter-subscriptions ``` makes it clearer that this endpoint handles subscription actions, improving the overall API design.
I updated the relevant unit tests to reflect the new route and ran them to ensure the change does not break existing functionality. I also manually tested the route using Postman to verify that the request …

fix: newsletter subscriptions endpoint

---

api/v1/routes/auth.py
api/v1/schemas/organisation.py
api/v1/schemas/user.py
api/v1/services/organisation.py

Since an organization is created after a user is registered, the payload returned should include the created organization, same for when a user logs in, the payload for the response would also return or include the user's organizations, and same goes for magic link login.
​
Since an organization is created after a user is registered, the payload returned should include the created organization, same for when a user logs in, the payload for the response would also return or include the user's organizations, and same goes for magic link login.
​
​
The frontend needs to display the organizations a user belongs to when a user logs in or registers.
​
This was tested with pytest and postman
​
Test for pytest
test for registration payload
test for login
test for magic-link login
​
​

fix: Fixed The payload returned after authentication

---

api/v1/routes/auth.py
api/v1/services/organisation.py

This Change ensures that the verification link correctly directs a user to the correct frontend link for magic-link verification.
​
This Change ensures that the verification link correctly directs a user to the correct frontend link for magic-link verification.
​WIth this, The user is sent to the right page for further authentication.
​
​
​
The change did not break any tests,, all tests passed
​
pytest
​
​

chore: Updated the link to frontend for magic link verification.

---

api/core/dependencies/email/templates/base.html
api/v1/models/profile.py
api/v1/routes/profiles.py
api/v1/services/organisation.py
api/v1/services/regions.py
api/v1/services/user.py

This fix directly fixed the bug where a user profile is not returned when accessed. It correctly changes the endpoint from /profile/current_user to /profile/{user_d}, fixed the functionality for a user profile to be created on sign up.
​
This fix directly fixed the bug where a user profile is not returned when accessed. It correctly changes the endpoint from /profile/current_user to /profile/{user_d}, fixed the functionality for a user profile to be created on sign up.
​
​
This fix directly fixed the bug where a user profile is not returned when accessed. It correctly changes the endpoint from /profile/current_user to /profile/{user_d}, fixed the functionality for a user profile to be created on sign up.
​
This has been tested with pytest and postman.
​
user created successfully with …

fix: Fixed user profile information retrieval

---

api/v1/routes/auth.py
api/v1/schemas/user.py
api/v1/services/google_oauth.py
api/v1/services/organisation.py
api/v1/services/user.py

This pull requests fixes the error on the frontend where profile, data-privacy, organisation, and region are supposed to be created  and associated with a user(regardless of super admin) on sign up.
​
This pull requests fixes the error on the frontend where profile, data-privacy, organisation, and region are supposed to be created  and associated with a user(regardless of super admin) on sign up. With this fix, every super admin would have the added associations.
​
​
This pull requests fixes the error on the frontend where profile, data-privacy, organisation, and region are supposed to be created  and associated with a user(regardless of super admin) on sign up.
​
This has been tested with pytest and postman.
​
WITH PYTEST
SUPER ADMIN REGISTRATION ORGANISATION CREATED
SUPER ADMIN …

fix: Fixed super admin organisation, profile, region, data-privacy creation on sign up.

---

.github/workflows/cd.dev.yaml
.github/workflows/cd.prod.yaml
.github/workflows/cd.staging.yaml
.github/workflows/ci.yml

Ci-workflow

---

api/core/dependencies/email/templates/email_feedback.html
api/utils/send_mail.py

​
I added a sent feedback email to user's email address on filling the form as a confirmation to the user that their request has been recieved.
​
​
This change enhances user experience by providing immediate confirmation that their contact form submission has been successfully received, reducing uncertainty and improving communication with users.
​
​
​
​

chore: send post contact feedback email

---

api/core/dependencies/email/templates/newsletter-subscription.html
api/v1/routes/newsletter.py
api/v1/services/newsletter.py
tests/v1/newsletter/test_newsletter_subscribe.py

This pull request solves the previous situation where no email is sent to a user when they subscribe to newsletter.
​
This pull request solves the previous situation where no email is sent to a user when they subscribe to newsletter.
With this fix, emails are now been sent to users on newsletter-subscriptions.
​
[newsletter subscription email](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/836)
​
Users need to get a confirmation email on or after subscribing to a newsletter.
​
This has been tested with pytest and postman.
​
​EMAIL IS SENT TO USER
EMAIL IS RECEIVED BY THE USER
​

fix: newsletter email verification subscription

---

api/v1/routes/auth.py
api/v1/routes/user.py
api/v1/schemas/user.py

This pull request is intended to move the /api/v1/users/me to /api/v1/auth/@me in accordance with the C# docs.
​
This pull request is intended to move the /api/v1/users/me to /api/v1/auth/@me in accordance with the C# docs.
​
[Move /users/me to /auth/@me](https://github.com/hngprojects/hng_boilerplate_python_fastapi_web/issues/922)
​
​
This fix has been tested with pytest and postman
​
​
​

fix: moved /api/v1/users/me to /api/v1/auth/@me

---

qa_tests/Boilerplate-status-page.postman_collection.json

For boilerplate status page report

boilerplate status page

---

api/v1/routes/google_login.py
api/v1/routes/stripe.py
api/v1/services/google_oauth.py
api/v1/services/payment.py
api/v1/services/user.py
tests/v1/auth/test_google_auth.py
tests/v1/test_google_oauth.py

​
This pull request improves the Google OAuth flow by adding enhanced error handling and user creation. The changes include:
- Improved error handling for invalid ID tokens and failed authorization code exchanges
- Creation of a new user if they don't exist during the OAuth flow
- Generation of access and refresh tokens for the user
- Setting of refresh token cookie with secure and httponly flags
​
https://github.com/hngprojects/hng_boilerplate_nestjs/issues/884
​
The current Google OAuth flow had some issues with error handling and user creation. This pull request aims to improve the flow by adding robust error handling and creating a new user if they don't exist. This will improve the overall user experience and security of the application.
​
I have tested the changes by running the …

Bugfix: improved Google OAuth flow with enhanced error handling and user creation

---

api/v1/routes/payment.py
tests/v1/payment/test_get_payments_for_current_user.py
tests/v1/payment/test_payment.py

This update adds an endpoint to get a user transaction history by the user's ID
​
[issue](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/877)
​
creating a new transactions history endpoint that follows the c sharp documentation
​
-This has been tested with postman 
-This has been tested with pytest
​
​
​

feat : endpoint To to [GET] transaction history for a user by the user ID

---

api/v1/routes/faq.py
api/v1/services/faq.py
tests/v1/faq/get_all_faqs_test.py

​
​This PR introduces the functionality to organize and fetch FAQs based on categories. The changes include modifications to the existing FAQ service to support grouping FAQs by their categories.
[[ENHANCEMENT] [ANCHOR : BE Python] Endpoint and structure for Catergory Based Organization for FAQ Page​](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/920)
​This change is required to provide a better user experience on the FAQ page by categorizing FAQs. It allows users to easily find answers to their questions by browsing through relevant categories.
The changes have been tested using unit tests and Postman
​
​
​

feat: Add Category-Based Organization for FAQ Page

---

api/v1/routes/regions.py
api/v1/services/regions.py

​
This update addresses an issue where duplicate time zone entries appeared in the dropdown menu on the Language & Region settings page of the Admin Dashboard. The service logic has been refactored to ensure that only unique time zones are retrieved and displayed in the dropdown.
​
This pull request resolves the issue related to duplicate time zone entries in 
the dropdown, as tracked in issue #943 
​
The change was necessary to eliminate confusion among users when selecting a time zone from the dropdown. Duplicates in the list could lead to errors or user frustration. By ensuring each time zone is listed only once, the user experience is improved, and potential errors are reduced.
​
The changes were tested using Postman to verify the `api/v1/regions/` endpoint returns only unique time …

feat: fixed duplicate timezones

---

api/v1/routes/newsletter.py
requirements.txt

This pull request fixes the constant ending of emails to users and visitors that subscribes to newsletters.
​
This pull request fixes the constant ending of emails to users and visitors that subscribes to newsletters.
With this fix, only newsletter subscribers that are subscribing for the first time would receive a notification email.
​
[newsletter fix](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/960)
​
​
This has been tested with postman. The pytest for this already exists.
​
USER SUBSCRIBE FOR THE FIRST TIME
​USER TRIES TO SUBSCRIBE AGAIN
​

fix: Fixed sending of emails to only new newsletter-subscribers.

---

.github/workflows/regression-test.yml

Update regression workflow

---

api/v1/routes/dashboard.py
api/v1/routes/product.py
api/v1/services/product.py
tests/v1/product/test_product_search.py

​
​This change implements the search functionality for products on the user or super admin dashboard
[Product Search​](https://github.com/hngprojects/hng_boilerplate_nestjs/issues/1007)
​This allows a user to be able to search for a specific product.
​Tests were carried out using untitests
​
​

feat: implement product search on dashboard

---

.github/workflows/regression-test.yml

Update regression-test workflow to only run on workflow dispatch
